parameters:
    knp_menu_item.class: Knp\Menu\MenuItem

services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            -  @csa_guzzle.client.local_api
            -  @front.http.request_builder

    front.authentication.success_handler:
        class:     FrontBundle\Security\Http\Authentication\AuthenticationSuccessHandler
        arguments: [ @security.http_utils ]
        calls:     [ [ setJwtManager, [ @lexik_jwt_authentication.jwt_manager ] ] ]

    front.http.request_builder:
        class: FrontBundle\Services\Http\RequestBuilder
        arguments: [ @front.http.url_builder, %front_base_url% ]

    front.http.url_builder:
        class:     FrontBundle\Services\Http\UrlBuilder
        arguments: [ @router ]

    front.twig_extension:
        class:  FrontBundle\Twig\FrontExtension
        public: false
        tags:   [ { name: twig.extension } ]

    #
    # KNP Menus
    #
    # @see http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html
    #
    front.menu_builder:
        class: FrontBundle\Menu\MenuBuilder
        arguments:
            -  @knp_menu.factory
            -  @security.authorization_checker
            -  @security.token_storage

    front.menu.header:
        class:     %knp_menu_item.class%
        factory:   [ @front.menu_builder, createHeaderMenu ]
        arguments: [ @request_stack, @knp_menu.factory ]
        tags:      [ { name: knp_menu.menu, alias: header_menu } ]

    front.menu.user:
        class:     %knp_menu_item.class%
        factory:   [ @front.menu_builder, createUserMenu ]
        arguments: [ @request_stack, @knp_menu.factory ]
        tags:      [ { name: knp_menu.menu, alias: user_menu } ]
