imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect:    false

# If later a different database name is needed for tests, should be done here
doctrine:
    dbal:
        dbname: %database_name%_test

# Doctrine Extensions
stof_doctrine_extensions:
    class:
        # Overrides Timestampable listener to set fix values for createAt and updatedAt dates to ease the testing
        timestampable:  ApiBundle\Test\Mock\EventListener\TimestampableListenerMock
    orm:
        default:
            timestampable: true

# SwiftMailer
swiftmailer:
    disable_delivery: true

# Web Profiler
web_profiler:
    toolbar:             false
    intercept_redirects: false
